services:
  saferase-dev:
    build: .
    container_name: saferase-pro-dev
    volumes:
      # Mount current directory for development
      - .:/app
    # Keep container running for development
    tty: true
    stdin_open: true
    # Environment variables
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # Override default command to keep container running
    command: tail -f /dev/null
